// AUTO-GENERATED by gen_proto.py — do not edit by hand
// Re-run gen_proto.py whenever packets.py changes.
#pragma once
#include <stdint.h>
#include <string.h>

// ── packet ids ───────────────────────────────────────────────────────────────

typedef enum
{
    PACKET_ID_RAW_STATE = 0,
    PACKET_ID_CALIBRATED_STATE = 1,
    PACKET_ID_ERROR = 2,
    PACKET_ID_MISO_ECHO = 3,
} miso_packet_id_t;

typedef enum
{
    PACKET_ID_STOP = 0,
    PACKET_ID_SET_GAINS = 1,
    PACKET_ID_MOSI_ECHO = 2,
} mosi_packet_id_t;

// ── packet lists (X-macros) ──────────────────────────────────────────────────

#define MISO_PACKET_LIST                                                                     \
    X(RAW_STATE, 0, F(uint16_t, adc3_raw) F(uint16_t, adc4_raw) F(int32_t, angle_raw))       \
    X(CALIBRATED_STATE, 1, F(float, adc3_cal) F(float, adc4_cal) F(int64_t, angle_mdeg_cal)) \
    X(ERROR, 2, F(uint8_t, err_encoder))                                                     \
    X(MISO_ECHO, 3, F(uint8_t, echo))

#define MOSI_PACKET_LIST                                      \
    X(STOP, 0, F(uint32_t, stop))                             \
    X(SET_GAINS, 1, F(float, angle_alpha) F(float, kalman_q)) \
    X(MOSI_ECHO, 2, F(uint8_t, echo))

// ── payload structs ──────────────────────────────────────────────────────────

#define F(type, name) type name;
#define X(NAME, ID, FIELDS) \
    typedef struct          \
    {                       \
        FIELDS              \
    } miso_payload_##NAME##_t;
MISO_PACKET_LIST
#undef X

#define X(NAME, ID, FIELDS) \
    typedef struct          \
    {                       \
        FIELDS              \
    } mosi_payload_##NAME##_t;
MOSI_PACKET_LIST
#undef X
#undef F

// ── MISO send helpers ────────────────────────────────────────────────────────

#define MISO_SEND_RAW_STATE(ts, _adc3_raw, _adc4_raw, _angle_raw) \
    do                                                            \
    {                                                             \
        miso_payload_RAW_STATE_t _p = {                           \
            .adc3_raw = (_adc3_raw),                              \
            .adc4_raw = (_adc4_raw),                              \
            .angle_raw = (_angle_raw),                            \
        };                                                        \
        packet_t _pkt = {                                         \
            .id = PACKET_ID_RAW_STATE,                            \
            .timestamp = (ts),                                    \
            .len = sizeof(miso_payload_RAW_STATE_t),              \
        };                                                        \
        memcpy(_pkt.data, &_p, _pkt.len);                         \
        usb_packet_enqueue_from_isr(&_pkt);                       \
    } while (0)

#define MISO_SEND_CALIBRATED_STATE(ts, _adc3_cal, _adc4_cal, _angle_mdeg_cal) \
    do                                                                        \
    {                                                                         \
        miso_payload_CALIBRATED_STATE_t _p = {                                \
            .adc3_cal = (_adc3_cal),                                          \
            .adc4_cal = (_adc4_cal),                                          \
            .angle_mdeg_cal = (_angle_mdeg_cal),                              \
        };                                                                    \
        packet_t _pkt = {                                                     \
            .id = PACKET_ID_CALIBRATED_STATE,                                 \
            .timestamp = (ts),                                                \
            .len = sizeof(miso_payload_CALIBRATED_STATE_t),                   \
        };                                                                    \
        memcpy(_pkt.data, &_p, _pkt.len);                                     \
        usb_packet_enqueue_from_isr(&_pkt);                                   \
    } while (0)

#define MISO_SEND_ERROR(ts, _err_encoder)        \
    do                                           \
    {                                            \
        miso_payload_ERROR_t _p = {              \
            .err_encoder = (_err_encoder),       \
        };                                       \
        packet_t _pkt = {                        \
            .id = PACKET_ID_ERROR,               \
            .timestamp = (ts),                   \
            .len = sizeof(miso_payload_ERROR_t), \
        };                                       \
        memcpy(_pkt.data, &_p, _pkt.len);        \
        usb_packet_enqueue_from_isr(&_pkt);      \
    } while (0)

#define MISO_SEND_MISO_ECHO(ts, _echo)               \
    do                                               \
    {                                                \
        miso_payload_MISO_ECHO_t _p = {              \
            .echo = (_echo),                         \
        };                                           \
        packet_t _pkt = {                            \
            .id = PACKET_ID_MISO_ECHO,               \
            .timestamp = (ts),                       \
            .len = sizeof(miso_payload_MISO_ECHO_t), \
        };                                           \
        memcpy(_pkt.data, &_p, _pkt.len);            \
        usb_packet_enqueue_from_isr(&_pkt);          \
    } while (0)

// ── MOSI recieve helpers ────────────────────────────────────────────────────────

__attribute__((weak)) void mosi_handle_STOP(uint32_t ts, uint32_t _stop);
__attribute__((weak)) void mosi_handle_SET_GAINS(uint32_t ts, float _angle_alpha, float _kalman_q);
__attribute__((weak)) void mosi_handle_MOSI_ECHO(uint32_t ts, uint8_t _echo);

static inline void mosi_dispatch(uint32_t ts, uint8_t packet_id, const uint8_t *buf)
{
    switch (packet_id)
    {
    case PACKET_ID_STOP:
    {
        uint32_t _stop;
        memcpy(&_stop, buf + 0, sizeof(uint32_t));
        mosi_handle_STOP(ts, _stop);
        break;
    }
    case PACKET_ID_SET_GAINS:
    {
        float _angle_alpha;
        memcpy(&_angle_alpha, buf + 0, sizeof(float));
        float _kalman_q;
        memcpy(&_kalman_q, buf + 4, sizeof(float));
        mosi_handle_SET_GAINS(ts, _angle_alpha, _kalman_q);
        break;
    }
    case PACKET_ID_MOSI_ECHO:
    {
        uint8_t _echo;
        memcpy(&_echo, buf + 0, sizeof(uint8_t));
        mosi_handle_MOSI_ECHO(ts, _echo);
        break;
    }
    }
}